build: 
  environment: 
    php: 
      version: "5.6.9"
  tests: 
    override: 
      - 
        command: "bin/phpspec run -f progress -c phpspec.yml"
        coverage: 
          file: coverage.clover
          format: php-clover
      -
        command: "bin/phpunit --coverage-clover=coverage_integration.clover"
        coverage:
          file: coverage_integration.clover
          format: php-clover