build:
  tests:
    override:
      -
        command: 'bin/phpspec run -f progress -c phpspec.yml'
        coverage:
          file: 'coverage.clover'
    environment:
        php:
            version: 5.6.9