language: php

php:
    - 5.6
    - 7.0

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

install:
    - travis_retry composer install

script:
    - ./bin/phpspec run
    - ./bin/phpunit